export const FETCH_SALA_REQUEST = "FETCH_SALA_REQUEST";
export const FETCH_SALA_SUCCESS = "FETCH_SALA_SUCCESS";

export const ADD_SALA_REQUEST = "ADD_SALA_REQUEST";

export const DELETE_SALA_REQUEST = "DELETE_SALA_REQUEST";
export const DELETE_SALA_SUCCESS = "DELETE_SALA_SUCCESS";

export const UPDATE_SALA_REQUEST = "UPDATE_SALA_REQUEST";
export const UPDATE_SALA_SUCCESS = "UPDATE_SALA_SUCCESS";
export const UPDATE_SALA_ERROR = "UPDATE_SALA_ERROR";
