export const FETCH_MANTENIMIENTO_REQUEST = "FETCH_MANTENIMIENTO_REQUEST";
export const FETCH_MANTENIMIENTO_SUCCESS = "FETCH_MANTENIMIENTO_SUCCESS";

export const ADD_MANTENIMIENTO_REQUEST = "ADD_MANTENIMIENTO_REQUEST";

export const DELETE_MANTENIMIENTO_REQUEST = "DELETE_MANTENIMIENTO_REQUEST";
export const DELETE_MANTENIMIENTO_SUCCESS = "DELETE_MANTENIMIENTO_SUCCESS";

export const UPDATE_MANTENIMIENTO_REQUEST = "UPDATE_MANTENIMIENTO_REQUEST";
export const UPDATE_MANTENIMIENTO_SUCCESS = "UPDATE_MANTENIMIENTO_SUCCESS";
export const UPDATE_MANTENIMIENTO_ERROR = "UPDATE_MANTENIMIENTO_ERROR";
