export const FETCH_CONFIGURACION_REQUEST = "FETCH_CONFIGURACION_REQUEST";
export const FETCH_CONFIGURACION_SUCCESS = "FETCH_CONFIGURACION_SUCCESS";

export const ADD_CONFIGURACION_REQUEST = "ADD_CONFIGURACION_REQUEST";

export const DELETE_CONFIGURACION_REQUEST = "DELETE_CONFIGURACION_REQUEST";
export const DELETE_CONFIGURACION_SUCCESS = "DELETE_CONFIGURACION_SUCCESS";

export const UPDATE_CONFIGURACION_REQUEST = "UPDATE_CONFIGURACION_REQUEST";
export const UPDATE_CONFIGURACION_SUCCESS = "UPDATE_CONFIGURACION_SUCCESS";
export const UPDATE_CONFIGURACION_ERROR = "UPDATE_CONFIGURACION_ERROR";
