export const FETCH_EQUIPOS_RESPALDO_REQUEST = "FETCH_EQUIPOS_RESPALDO_REQUEST";
export const FETCH_EQUIPOS_RESPALDO_SUCCESS = "FETCH_EQUIPOS_RESPALDO_SUCCESS";

export const ADD_EQUIPOS_RESPALDO_REQUEST = "ADD_EQUIPOS_RESPALDO_REQUEST";

export const DELETE_EQUIPOS_RESPALDO_REQUEST =
  "DELETE_EQUIPOS_RESPALDO_REQUEST";
export const DELETE_EQUIPOS_RESPALDO_SUCCESS =
  "DELETE_EQUIPOS_RESPALDO_SUCCESS";

export const UPDATE_EQUIPOS_RESPALDO_REQUEST =
  "UPDATE_EQUIPOS_RESPALDO_REQUEST";
export const UPDATE_EQUIPOS_RESPALDO_SUCCESS =
  "UPDATE_EQUIPOS_RESPALDO_SUCCESS";
export const UPDATE_EQUIPOS_RESPALDO_ERROR = "UPDATE_EQUIPOS_RESPALDO_ERROR";
