export const FETCH_DISPOSITIVOS_REQUEST = "FETCH_DISPOSITIVOS_REQUEST";
export const FETCH_DISPOSITIVOS_SUCCESS = "FETCH_DISPOSITIVOS_SUCCESS";

export const ADD_DISPOSITIVOS_REQUEST = "ADD_DISPOSITIVOS_REQUEST";

export const DELETE_DISPOSITIVOS_REQUEST = "DELETE_DISPOSITIVOS_REQUEST";
export const DELETE_DISPOSITIVOS_SUCCESS = "DELETE_DISPOSITIVOS_SUCCESS";

export const UPDATE_DISPOSITIVOS_REQUEST = "UPDATE_DISPOSITIVOS_REQUEST";
export const UPDATE_DISPOSITIVOS_SUCCESS = "UPDATE_DISPOSITIVOS_SUCCESS";
export const UPDATE_DISPOSITIVOS_ERROR = "UPDATE_DISPOSITIVOS_ERROR";
