export const FETCH_UBICACION_REQUEST = "FETCH_UBICACION_REQUEST";
export const FETCH_UBICACION_SUCCESS = "FETCH_UBICACION_SUCCESS";

export const ADD_UBICACION_REQUEST = "ADD_UBICACION_REQUEST";

export const DELETE_UBICACION_REQUEST = "DELETE_UBICACION_REQUEST";
export const DELETE_UBICACION_SUCCESS = "DELETE_UBICACION_SUCCESS";

export const UPDATE_UBICACION_REQUEST = "UPDATE_UBICACION_REQUEST";
export const UPDATE_UBICACION_SUCCESS = "UPDATE_UBICACION_SUCCESS";
export const UPDATE_UBICACION_ERROR = "UPDATE_UBICACION_ERROR";
